### ISSUE TITLE
Admin settings dialog for setting iop_url and shared_secret

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-php#121]

**Comment by michielbdejong** [comment]
With this, we will not have to rely on [sql insert statements](https://github.com/cs3org/ocm-test-suite/blob/1704e6d/scripts/start-from-Revanc.sh#L26-L28) anymore.

**Comment by navid-dada** [comment]
https://docs.nextcloud.com/server/latest/developer_manual/basics/setting.html

**Comment by michielbdejong** [comment]
That's for Nextcloud. For ownCloud I found [this](https://doc.owncloud.com/server/next/developer_manual/app/fundamentals/configuration.html).

**Comment by navid-dada** [comment]
Oh!!! I found this two.
https://doc.owncloud.com/server/next/admin_manual/appliance/configuration/app_settings.html

**Comment by parhamin2010** [comment]
https://github.com/nextcloud/twofactor_webauthn/
Contribute with Navid to find a sample as new setting dialogue for this integration

**Comment by parhamin2010** [comment]
FOUND IT!
- The settings menu item has been added based on this instruction on NC
https://docs.nextcloud.com/server/latest/developer_manual/basics/setting.html
- The template is added
- Route is added

**Comment by michielbdejong** [comment]
The code for this still needs to be pushed and merged on both repos

**Comment by michielbdejong** [comment]
@navid-dada I discussed with @parhamin2010 just now that Loopback Secret should be read-only but Shared Secret and IP URL should be editable, do you agree?

**Comment by michielbdejong** [comment]
I heard from Parham that you took a different design decision about this earlier, but it probably wasn't documented anywhere, right?

**Comment by michielbdejong** [comment]
This was closed automatically by GitHub because it's done for NC
Reopening because it's not done for OC

**Comment by michielbdejong** [comment]
@parhamin2010 copying this here onto the issue (you wrote this in the Google Meet):
> doc for new custom configuration:
> https://doc.owncloud.com/server/next/developer_manual/app/fundamentals/configuration.html

**Comment by parhamin2010** [comment]
Instruction for create custom settings in OC:
step 1: Add settings section inside appinfo.xml like below
`
    <settings>
        <admin>OCA\ScienceMesh\Settings\SciencemeshSettingsAdmin</admin>
    </settings>
	<settings-sections>
        <admin>OCA\ScienceMesh\Sections\SciencemeshSettingsAdmin</admin>
	</settings-sections>`

**Comment by michielbdejong** [comment]
Fixed for OC in https://github.com/pondersource/oc-sciencemesh/pull/40

**Comment by michielbdejong** [comment]
@parhamin2010 can this issue be closed now?

**Comment by parhamin2010** [comment]
> @parhamin2010 can this issue be closed now?

yes, this one is completed.

**Comment by michielbdejong** [comment]
Split into pondersource/nc-sciencemesh#240 and pondersource/oc-sciencemesh#47
