### ISSUE TITLE
Check provider domains

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-php#137]
* [x] [WWU](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=uni-muenster.de)
* [x] [CESNET](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=sciencemesh.cesnet.cz)
* [x] [CESNET-TEST](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=sciencemesh-test.cesnet.cz)
* [x] [CERN](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=cern.ch)
* [x] [SURF_DEPRICATED](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=surfsara.nl)
* [x] [SURF_IOP_OC](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=surf-iop-rd-app-acc.data.surfsara.nl)
* [x] [SURF_IOP_EXP](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=thirsa.nl)
* [x] [CUBBIT](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=cubbit.io)
* [x] [AILLERON](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=sciencemesh.softwaremind.com)
* [x] [SWITCH](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=switch.ch)
* [x] [DTU](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=dtu.dk)
* [x] [PONDERSOURCE](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=mesh.pondersource.org)
* [x] [pondersource-test](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=mesh.pondersource.com)
* [x] [PSNC](https://sciencemesh.cesnet.cz/iop/meshdir?token=asdf&providerDomain=cs3mesh-iop.apps.dcw1.paas.psnc.pl)

**Comment by michielbdejong** [comment]
Accept to:
* [x] [Ailleron/Softwaremind](https://nextcloud.softwaremind.com/index.php/login?redirect_url=/index.php/apps/sciencemesh/accept?token%3Dasdf%26providerDomain%3Dmesh.pondersource.org) NC
* [ ] [CERN]() sciencemesh.cernbox.cern.ch took too long to respond.
* [x] [CESNET](https://oc-mesh.du.cesnet.cz/login?redirect_url=%252Findex.php%252Fapps%252Fsciencemesh%252Faccept%253Ftoken%253Dasdf%2526providerDomain%253Dmesh.pondersource.org) OC
* [ ] [CESNET testing](https://sciencemesh-test.cesnet.cz/iop/ocm/invites/forward?token=asdf&providerDomain=mesh.pondersource.org) http basic auth
* [ ] [CUBBIT](https://sciencemesh.cubbit.io/ocm/invites/forward?token=asdf&providerDomain=mesh.pondersource.org) http basic auth

**Comment by labkode** [comment]
sciencemesh.cernbox.cern.ch is being revamped by the OCIS version, it will be operational as soon as we have it wired to production.

**Comment by michielbdejong** [comment]
Also SWITCH are in a maintenance window.
The others (crossed out) are test sites.

**Comment by michielbdejong** [comment]
The site that the 'accept' linke points to for WWU is https://uni-muenster.sciebo.de/ 
and this is not really a Science Mesh site yet, it doesn't have the sciencemesh app installed yet.
A separate test instance will be deployed soon.
