### ISSUE TITLE
'Email' in Science Mesh contacts is not really email

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-php#151]
It lists the opaque ID of the remote user (e.g. "einstein"). It should probably display "opaqueId@idp", so eg. "einstein@oc1.docker" and the column name should then be "Open Cloud Mesh Address" instead of "Email.

* [ ] for nc-sciencemesh
* [ ] for oc-sciencemesh

**Comment by michielbdejong** [comment]
![Screenshot 2023-02-01 at 13 07 23](https://user-images.githubusercontent.com/408412/216038444-accb9291-6be5-44b3-9731-7fc7da11f922.png)
![Screenshot 2023-02-01 at 13 07 44](https://user-images.githubusercontent.com/408412/216038455-c4db8b18-7268-4053-94da-f2c3fe0697c6.png)

**Comment by parhamin2010** [comment]
Fix added here:
https://github.com/pondersource/nc-sciencemesh/commit/45ce76d48c96013a8eb10a0f277a6ad455abb0e3
