### ISSUE TITLE
Collaborator search  in NC should do a rest call to basically ocm-find-accepted-users in Reva

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-php#40]

**Comment by ylebre** [comment]
Started this in https://github.com/pondersource/nc-sciencemesh/pull/132 - only needs the glue for the actual http call to Reva. Is there an example available of the data this would return?

**Comment by ylebre** [comment]
Example is available here: 
https://github.com/pondersource/sciencemesh-nextcloud/issues/53

**Comment by michielbdejong** [comment]
@ylebre this is working now, right? Can this issue be closed?
