### ISSUE TITLE
Correct ocm-forward URIs from meshdir

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-php#92]
It seems that from [meshdir](https://sciencemesh.cesnet.cz/iop/meshdir/?token=mytoken&providerDomain=uni-muenster.de) the end-user's browser gets redirected to reva; template: 
`https://<reva.site.com>/iop/ocm/invites/forward?token=<mytoken>&providerDomain=<uni-muenster.de>`

For CERN, the end-user's browser should instead be redirected to their OCIS GUI.

For all NC and OC-10 sites the end-user's browser should instead be redirected to their EFSS GUI, template: `https://<efss.site.com>/index.php/apps/sciencemesh/accept?token=<mytoken>&providerDomain=<uni-muenster.de>`
Or (depending on how the EFSS installation is configured):
`https://<efss.site.com>/apps/sciencemesh/accept?token=<mytoken>&providerDomain=<uni-muenster.de>`

**Comment by michielbdejong** [comment]
Careful, the `https://<reva.site.com>/iop/ocm/` prefix is still needed because it's where the Reva's machine-readable OCM API lives. But not for the human-readable GUI to which the end-user's browser should be redirected from meshdir.

**Comment by mirekys** [comment]
For this redirection to work reliably, we need to add another Service type to GOCDB/mentix providers metadata.
Currently the only thing referring to site's EFSS system seems to be the `WEBDAV`-type Service, but `apps/sciencemesh/` API could not be safely 'guessed' from that:

```json
{
  "host":"efss.site.com",
  "endpoint":{
    "type":{
      "name":"WEBDAV",
      "description":"Web Distributed Authoring and Versioning Service",
    },
    "name":"WEBDAV",
    "path":"https://efss.site.com/iop/remote.php/webdav",
  },
  "api_version":"0.1.0",
},

I would suggest adding the `EFSS` (I'm in a lack for better naming :)) service type pointing to the URL of the`sciencemesh` app API on that EFSS system.

@Daniel-WWU-IT @michielbdejong does that sound ok to you?

**Comment by michielbdejong** [comment]
Hm, I think `EFSS` doesn't convey the fact that it needs to point to the human-viewable web interface.
Also, within the web interface you need the full route of the dialog where the user can accept an invite, not just the base URL of the GUI.
For OC10 and NC this is `apps/sciencemesh/accept` but I don't know which route OCIS will use.
And then there is the issue of how to pass the parameters - but I think we can require that all web interfaces support the `?token=mytoken&providerDomain=uni-muenster.de` query parameters for this.

**Comment by Daniel-WWU-IT** [comment]
Adding a new service type is no big deal for me, we'd just need to get people to update their data... but they are responsible for this anyway, right? ;)

**Comment by Daniel-WWU-IT** [comment]
I'd not include the term 'Sciencemesh' in those names, as everything is Sciencemesh already.

**Comment by michielbdejong** [comment]
OK!

**Comment by david-antos** [comment]
@Daniel-WWU-IT are there any missing issues to discuss (Mirek agreed by thumbs up and Michiel explictly)? Or is it clear enough to make it happen? Thanks!

**Comment by Daniel-WWU-IT** [comment]
I'm not really involved much in the "make it happen" part here. If a new service type needs to be added to our meta data, I'll happily do so, I just need to know what name it should get (`EFSS_WEBAPP` or anything else) and where it should point to (for those sites which already provide that endpoint).

**Comment by mirekys** [comment]
> I'm not really involved much in the "make it happen" part here. If a new service type needs to be added to our meta data, I'll happily do so, I just need to know what name it should get (`EFSS_WEBAPP` or anything else) and where it should point to (for those sites which already provide that endpoint).

Let's make a new service type named `EFSS_WEBAPP`. This should point to the base URL of the integration (`{oc|nc}-sciencemesh`) app routes. For OC/NC EFSSs, we expect the value to be like: `https://<efss.site.com>/index.php/apps/sciencemesh/ `. It is the base path, under which the following routes are registered & expected to exist: https://github.com/pondersource/oc-sciencemesh/blob/main/appinfo/routes.php#L60-L64.

Once the site has an `EFSS_WEBAPP` service configured in mesh metadata, I'll make it happen on the meshdir side, that it makes a redirect to `${EFSS_WEBAPP}/accept?token=mytoken&providerDomain=uni-muenster.de`. If there is no `EFSS_WEBAPP` configured for a site, it'll fall back to use the current `ocm/invites` API...

Everyone happy with this? :) @Daniel-WWU-IT @michielbdejong @david-antos

**Comment by Daniel-WWU-IT** [comment]
Sounds good to me 👍

**Comment by labkode** [comment]
@Daniel-WWU-IT after discussing with @mirekys I think the best would be to:

- Rename the field from `EFSS_WEBAPP` to `EFSS_SCIENCEMESHAPP`
- Add a new field `EFSS_STATUS`

Examples:
```
EFSS_SCIENCEMESHAPP => https://iop.sciencemesh.uni-muenster.de/iop/index.php/apps/sciencemesh/
EFSS_STATUS => https://iop.sciencemesh.uni-muenster.de/iop/status.php
```

`EFSS_SCIENCEMESHAPP` to be used by meshdir to craft the callback url as describe above in this thread
`EFSS_STATUS` to be used in the central monitoring to track EFSS deployed versions

**Comment by Daniel-WWU-IT** [comment]
@mirekys @labkode 
I have added the new service types and also created an example instance for our site (WWU); just use this as a guideline. I also updated above documentation.

This also means that all previously added `EFSS_WEBAPP` instances must be added again, this time in the form of the new structure.

**Comment by Daniel-WWU-IT** [comment]
Awesome! :)

**Comment by mirekys** [comment]
@labkode it was too hard to do a reliable hover-on tooltip (it wouldn't even work on mobile) so I made it as a clickable icon triggering this dialog popup:
![Screenshot 2023-01-04 at 16 54 25](https://user-images.githubusercontent.com/646743/210595447-8a5d42ca-adf9-41a0-9bd4-e50c00291b82.jpg)

(it is already deployed)
