### ISSUE TITLE
meshdir caroussel hard to use from Chrome and Firefox

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-php#93]
When scrolling up in the caroussel using the arrow keys, it only moves up to SURF-EXP and then snaps back to the bottom of the list:
<img width="371" alt="Screenshot 2022-10-18 at 09 18 28" src="https://user-images.githubusercontent.com/408412/196363077-3bb49752-9bd9-499d-91cd-b93f1abdf152.png">
<img width="371" alt="Screenshot 2022-10-18 at 09 19 15" src="https://user-images.githubusercontent.com/408412/196363080-59d9fd26-c5f6-4ece-af8d-ccc9b55b9555.png">

When trying to scroll up using the "^" button, it's hard to click, it selects the underlying site instead

**Comment by michielbdejong** [comment]
@mirekys is working on this

**Comment by mirekys** [comment]
@michielbdejong Should be fixed in https://github.com/sciencemesh/meshdirectory-web/pull/27

**Comment by michielbdejong** [comment]
Yes!
